### ISSUE TITLE
Readme for Spark History Server is using the zeppelin as example

### ISSUE THREAD

**Issue by AzureQ** [SnappyDataInc/spark-on-k8s#1]

**Comment by sumwale** [comment]
@shyjaprabhu @ashetkar Can you take a look at the example as reported here? We should be documenting the non-zeppelin case first (while zeppelin should work without changes).

**Comment by ashetkar** [comment]
The Zeppelin example was added on purpose in README of Spark History Server chart, followed by the history server's example itself, so that users can view the Zeppelin job's  event logs in the History Server.

May be @dshirish can add more.

**Comment by sumwale** [comment]
@ashetkar Ok, maybe will be better to also add a non-zeppelin example first. @dshirish

**Comment by dshirish** [comment]
Will update and close the issue once the README is modified.

**Comment by dshirish** [comment]
Closing the issue as README has been changed (with instruction to use GCS)
