### ISSUE TITLE
 Spark History on s3

### ISSUE THREAD

**Issue by thbeh** [SnappyDataInc/spark-on-k8s#20]
Hi, assuming that I am not using GCP for Spark History but s3, what changes do I need for the  spark history chart? Thanks

**Comment by dshirish** [comment]
While we have not tested following settings should work. 

History server chart:
In the values.yaml of the history server (or umbrella chart if you use umbralla chart) point 'historyServerConf.eventsDir' to s3 bucket URL (s3a://bucket/folder). Also you will need to pass in secrets to access the s3 bucket by setting appropriate variables in 'environment.SPARK_HISTORY_OPTS' setting (-Dspark.hadoop.fs.s3a.access.key=... -Dspark.hadoop.fs.s3a.secret.key=...). You may also need to set -Dspark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem 

Spark job:
Launch you spark jobs with events logging enabled for example with following settings
    --conf spark.eventLog.dir=s3a://bucket/folder
    --conf spark.hadoop.fs.s3a.access.key=...
    --conf spark.hadoop.fs.s3a.secret.key=...
    --conf spark.eventLog.enabled=true

**Comment by thbeh** [comment]
Hi, how about SparkEvent Log in Zeppelin and Jupyter, should these be the same?

**Comment by thbeh** [comment]
Hi, testing the above looks like the required jar files for s3 is not in the container image. Would it be possible to share the dockerfile so that I can build an image with the require s3 jars. Thanks in advance.

**Comment by jramnara** [comment]
afaik, the required jars for S3 access are already in there.

But, here
<https://github.com/SnappyDataInc/spark-on-k8s/blob/298ca69e436703ec86ae8e732228bf10638f3836/docs/building-images.md>
are the instructions if you want to repackage and generate the image.

-----
Jags
SnappyData blog <http://www.snappydata.io/blog>
Download binary, source <https://www.snappydata.io/download>

**Comment by thbeh** [comment]
I will have a look. Wonder why it’s still complaining missing s3 class especially S3AFileSytem...
